### ISSUE TITLE
Error loading server extension sparkmonitor.serverextension

### ISSUE THREAD

**Issue by AlJohri** [krishnan-r/sparkmonitor#16]
My best guess is incompatibility with Tornado 6.

The root cause seems to be: `AttributeError: module 'tornado.web' has no attribute 'asynchronous'`:

https://github.com/krishnan-r/sparkmonitor/blob/b023845a245010fb7dd9c4be73747f0e5a8c93bd/extension/sparkmonitor/serverextension.py#L27

```
$ jupyter serverextension enable --py --sys-prefix sparkmonitor
Enabling: sparkmonitor.serverextension
- Writing config: /opt/anaconda3/etc/jupyter
    - Validating...
Error loading server extension sparkmonitor.serverextension
      X is sparkmonitor.serverextension importable?
```

```
$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sparkmonitor.serverextension
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/site-packages/sparkmonitor/serverextension.py", line 24, in <module>
    class SparkMonitorHandler(IPythonHandler):
  File "/opt/anaconda3/lib/python3.7/site-packages/sparkmonitor/serverextension.py", line 27, in SparkMonitorHandler
    @tornado.web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'
```

```
$ pip freeze | egrep "tornado|jupyter|spark"
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
jupyterlab==0.35.4
jupyterlab-server==0.2.0
sparkmonitor==0.0.9
tornado==6.0.2
```

**Comment by AlJohri** [comment]
related https://github.com/mozilla/jupyter-spark/issues/52#issuecomment-486515483

**Comment by IMAM9AIS** [comment]
I am running into a similar issue. Is their any immediate fix for this ?

**Comment by jahstreet** [comment]
Stucked with the same thing, are there any updates?

**Comment by krishnan-r** [comment]
I have fixed this in the master branch, will upload a new version to pypi with more changes soon.

**Comment by AlJohri** [comment]
Thanks @krishnan-r!

**Comment by AlJohri** [comment]
@krishnan-r can you cut a release?

using `pip install 'git+https://github.com/krishnan-r/sparkmonitor.git#egg=sparkmonitor&subdirectory=extension'` for now

EDIT: that didn't work- it can't find the `static` folder

**Comment by Ben-Epstein** [comment]
@AlJohri  I packaged it up and deployed it here if you'd like to use it: https://pypi.org/project/sparkmonitor-s/0.0.11/
:)

**Comment by vivekpayasi** [comment]
@Ben-Epstein Do we need to follow the installation instructions just like before or are there any changes in the commands?

**Comment by vivekpayasi** [comment]
It fixed the error. Thanks a lot @Ben-Epstein  :)

**Comment by Ben-Epstein** [comment]
@vivekpayasi  No changes required. Just run `pip install spark-monitor-s==0.0.11` and use the same instructions as the original.
