### ISSUE TITLE
when start kernel,will be throw the following error

### ISSUE THREAD

**Issue by wangqiaoshi** [krishnan-r/sparkmonitor#4]
when start kernel,will be throw the following error

> [W 11:26:28.271 NotebookApp] 404 GET /api/kernels/0ed75691-8a30-42ba-a856-8fd1f4a07446/channels?session_id=5890403E360A4F228A55153B574F22CB (::1): Kernel does not exist: 0ed75691-8a30-42ba-a856-8fd1f4a07446
[W 11:26:28.281 NotebookApp] 404 GET /api/kernels/0ed75691-8a30-42ba-a856-8fd1f4a07446/channels?session_id=5890403E360A4F228A55153B574F22CB (::1) 21.33ms referer=None
[W 11:26:32.297 NotebookApp] Replacing stale connection: 0ed75691-8a30-42ba-a856-8fd1f4a07446:5890403E360A4F228A55153B574F22CB
[I 11:26:33.917 NotebookApp] Kernel started: 0e6e9856-8288-4cc3-ae2e-2c5dd3d0d226
[W 11:26:33.932 NotebookApp] 404 GET /nbextensions/sparkmonitor/module.js?v=20180301112625 (::1) 8.88ms referer=http://localhost:8888/notebooks/Untitled7.ipynb
[W 11:26:34.104 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180301112625 (::1) 3.33ms referer=http://localhost:8888/notebooks/Untitled7.ipynb

**Comment by krishnan-r** [comment]
This could be a problem with configuration. Jupyter is unable to find the frontend javascript files. These files are a part of the python package. 
Which version of Jupyter are you using?

**Comment by wangqiaoshi** [comment]
4.3.0
![image](https://user-images.githubusercontent.com/2505074/36835506-6ba1aa0c-1d71-11e8-913c-f990e716052a.png)

**Comment by wangqiaoshi** [comment]
Thank you for your answer!
Problem has been solved！
